### ISSUE TITLE
Webjar references files with bugs in them, so it does not work right now.

### ISSUE THREAD

**Issue by geocolumbus** [webjars/syntaxhighlighter#1]
The minified files had several bug fixes incorporated that unfortunately don't appear to be in the non minified files. This webjar references the non-minified SyntaxHighlighter files.
#### Uncaught Error: Module name "XRegExp" has not been loaded yet for context: _. Use require([]).

see: http://stackoverflow.com/questions/25491122/is-xregexp-compatible-with-requirejs
#### shCore.js has this unfortunate line break around line 741, which causes an error "cannot read replace of undefined":

var value = match.value
            .replace(/^['"]|['"]$/g, '') // strip quotes from end of strings
            ;

**Comment by jamesward** [comment]
WebJars just package up an existing library.  So do you need a new version of this WebJar?

**Comment by geocolumbus** [comment]
I'll test when I get back. Technically I need the syntax highlighter team
to fix some bugs. I will let you know how I make out with it.

Regards,
George Campbell

**Comment by jamesward** [comment]
Cool.  Feel free to send a version bump request when they publish a new version with the fixes.
